"use client";

import { useState } from "react";

type DreamEntry={id:number;date:string;title:string;dream:string;mood:string;result:{summary:string;elements:string[]}};
type SeriesResult={overview:string;recurringMotifs:Array<{motif:string;appearances:string;development:string}>;freudPattern:string;jungPattern:string;timeline:string[];questions:string[];caution:string};

export default function DreamSeries({history,apiKey}:{history:DreamEntry[];apiKey:string}){
  const[selected,setSelected]=useState<number[]>([]);const[result,setResult]=useState<SeriesResult|null>(null);const[loading,setLoading]=useState(false);const[selecting,setSelecting]=useState(false);const[selectionReason,setSelectionReason]=useState("");const[error,setError]=useState("");
  const toggle=(id:number)=>setSelected(x=>x.includes(id)?x.filter(n=>n!==id):[...x,id]);
  async function selectWithAI(){
    if(!apiKey.trim()){setError("右上のBYOK / API KEYからOpenAI APIキーを設定してください。");return}setSelecting(true);setError("");
    try{const catalog=history.slice(0,30).map(x=>`ID:${x.id}\n日付:${x.date}\n夢:${x.dream}\n要素:${x.result.elements.join("、")}`).join("\n---\n");const schema={type:"object",properties:{selected_ids:{type:"array",items:{type:"integer"}},reason:{type:"string"}},required:["selected_ids","reason"],additionalProperties:false};const res=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey.trim()}`},body:JSON.stringify({model:"gpt-5-mini",input:`次の夢の記録から、共通モチーフや変化を連作として読む価値が高い夢を2〜8件選んでください。人物・場所・感情・構造の反復や対照を重視し、存在するIDだけ返してください。\n\n${catalog}`,text:{format:{type:"json_schema",name:"dream_selection",strict:true,schema}}})});if(!res.ok)throw new Error(`API error ${res.status}`);const data=await res.json();const outputText=data.output_text||data.output?.flatMap((x:{content?:Array<{type?:string;text?:string}>})=>x.content||[]).find((x:{type?:string})=>x.type==="output_text")?.text;if(!outputText)throw new Error("選択結果が空でした。");const parsed=JSON.parse(outputText);const valid=(parsed.selected_ids as number[]).filter(id=>history.some(x=>x.id===id));if(valid.length<2)throw new Error("関連する夢を2件以上選べませんでした。");setSelected(valid);setSelectionReason(parsed.reason)}catch(err){setError(`自動選択できませんでした：${err instanceof Error?err.message:"不明なエラー"}`)}finally{setSelecting(false)}
  }
  async function analyzeSeries(){
    if(selected.length<2){setError("2件以上の夢を選んでください。");return}if(!apiKey.trim()){setError("右上のBYOK / API KEYからOpenAI APIキーを設定してください。");return}
    setLoading(true);setError("");const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),60000);
    try{
      const dreams=history.filter(x=>selected.includes(x.id)).sort((a,b)=>a.date.localeCompare(b.date)).map((x,i)=>`夢${i+1}（${new Date(x.date).toLocaleDateString("ja-JP")}／気分:${x.mood}）\n${x.dream}\n初回分析:${x.result.summary}`).join("\n\n---\n\n");
      const prompt=`以下は同じ人物が記録した複数の夢です。単発の夢辞典式解釈をせず、夢の連作として時系列に分析してください。\n\n${dreams}\n\n内部では、反復、日中残滓、願望、葛藤、夢の加工、補償の推移、反復する像、意識的態度との関係、夢の連作における変容を別々に検討してください。そのうえでoverview、モチーフ、時系列、問いを統合された一つの読み解きとして提示してください。個人的連想がない事項は断定せず、診断・予言は禁止です。出力では人物名、学派名、理論名、二つの視点という表現を一切使わず、日本語の指定JSONのみ返してください。`;
      const schema={type:"object",properties:{overview:{type:"string"},recurringMotifs:{type:"array",items:{type:"object",properties:{motif:{type:"string"},appearances:{type:"string"},development:{type:"string"}},required:["motif","appearances","development"],additionalProperties:false}},freudPattern:{type:"string"},jungPattern:{type:"string"},timeline:{type:"array",items:{type:"string"}},questions:{type:"array",items:{type:"string"}},caution:{type:"string"}},required:["overview","recurringMotifs","freudPattern","jungPattern","timeline","questions","caution"],additionalProperties:false};
      const res=await fetch("https://api.openai.com/v1/responses",{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${apiKey.trim()}`},body:JSON.stringify({model:"gpt-5-mini",input:prompt,text:{format:{type:"json_schema",name:"dream_series_analysis",strict:true,schema}}})});
      if(!res.ok){const detail=await res.json().catch(()=>null);throw new Error(detail?.error?.message||`API error ${res.status}`)}const data=await res.json();const outputText=data.output_text||data.output?.flatMap((x:{content?:Array<{type?:string;text?:string}>})=>x.content||[]).find((x:{type?:string})=>x.type==="output_text")?.text;if(!outputText)throw new Error("分析結果が空でした。");setResult(JSON.parse(outputText));setTimeout(()=>document.querySelector(".seriesResult")?.scrollIntoView({behavior:"smooth",block:"start"}),80);
    }catch(err){setError(err instanceof DOMException&&err.name==="AbortError"?"複数夢の分析が60秒以内に完了しませんでした。":`分析できませんでした：${err instanceof Error?err.message:"不明なエラー"}`)}finally{clearTimeout(timeout);setLoading(false)}
  }
  if(history.length<2)return <section className="seriesTool emptySeries"><h2>複数の夢をまとめて読む</h2><p>夢を2件以上記録すると、反復する象徴と時系列の変化を分析できます。</p></section>;
  return <section className="seriesTool"><div className="sectionLabel"><span>SERIES</span>DREAM CONSTELLATION</div><h2>複数の夢をまとめて読む</h2><p>AIに関連する夢を選ばせるか、分析したい夢を2件以上選択してください。</p><button className="aiSelect" disabled={selecting||loading} onClick={selectWithAI}>{selecting?"AIが夢の関連を探索中…":"AIに関連する夢を選ばせる"}<b>✦</b></button>{selectionReason&&<p className="selectionReason"><strong>AIの選択理由</strong>{selectionReason}</p>}<div className="seriesPicker">{history.map(x=><label className={selected.includes(x.id)?"selected":""} key={x.id}><input type="checkbox" checked={selected.includes(x.id)} onChange={()=>toggle(x.id)}/><time>{new Date(x.date).toLocaleDateString("ja-JP")}</time><strong>{x.title}</strong><small>{x.result.summary}</small></label>)}</div>{error&&<p className="error">{error}</p>}<button className="seriesAnalyze" disabled={loading||selected.length<2} onClick={analyzeSeries}>{loading?"複数の夢を分析中…":`${selected.length}件の夢をまとめて分析する`}<b>→</b></button>{result&&<SeriesReport result={result}/>}</section>;
}

function SeriesReport({result}:{result:SeriesResult}){return <div className="seriesResult"><div className="seriesComplete">✓ 夢の連作分析が完了しました</div><h3>{result.overview}</h3><div className="motifTable"><div className="motifHead"><span>反復するモチーフ</span><span>現れ方</span><span>変化</span></div>{result.recurringMotifs.map((x,i)=><div key={`${x.motif}-${i}`}><strong>{x.motif}</strong><p>{x.appearances}</p><p>{x.development}</p></div>)}</div><div className="seriesLenses"><article><small>FREUD / REPETITION</small><h4>反復と夢の仕事</h4><p>{result.freudPattern}</p></article><article><small>JUNG / DREAM SERIES</small><h4>補償の推移と変容</h4><p>{result.jungPattern}</p></article></div><div className="seriesTimeline"><h4>時系列で見た変化</h4><ol>{result.timeline.map(x=><li key={x}>{x}</li>)}</ol></div><div className="seriesQuestions"><h4>次の夢へ持ち越す問い</h4>{result.questions.map(x=><p key={x}>→ {x}</p>)}</div><p className="seriesCaution">{result.caution}</p></div>}
