"use client";
import {useEffect,useMemo,useState} from "react";
import Questionnaire from "./Questionnaire";
import DreamSeries from "./DreamSeries";
import JournalExport from "./JournalExport";
import AnalysisClosure from "./AnalysisClosure";
import UnifiedResult from "./UnifiedResult";
import Approach from "./Approach";
import DiagnosisTimeline from "./DiagnosisTimeline";
type Lens="freud"|"jung"|"compare"; type Analysis={summary:string;elements:string[];freud:{manifest:string;latent:string;mechanisms:string[];questions:string[]};jung:{compensation:string;subjective:string;motifs:string[];questions:string[]};synthesis:string}; type Entry={id:number;date:string;title:string;dream:string;mood:string;lens:Lens;result:Analysis;initialResult?:Analysis;finalResult?:Analysis;associations?:string};
const DEMO:Analysis={summary:"水に沈む古い家と、開かない扉が中心となる夢。焦りと懐かしさが同時に現れています。",elements:["古い家","上昇する水","鍵のない扉","幼少期の友人","焦り／懐かしさ"],freud:{manifest:"記憶された筋書きは、古い家から脱出しようとする場面です。",latent:"家・扉・水が何を代理しているかは、夢を見た人の自由連想から検討します。固定的な記号表は使いません。",mechanisms:["凝縮：家に複数の時代や場所が重なっている可能性","置換：人物への感情が扉や水の危機へ移された可能性","表象可能性：抽象的な葛藤が視覚的な脱出場面へ変換された可能性","二次加工：目覚めた後に一貫した物語として整えられた可能性"],questions:["古い家から最初に連想する記憶は何ですか？","最近『開けない／進めない』と感じた場面はありますか？"]},jung:{compensation:"日中に統制や合理性を重視しているなら、制御できない水の像がその一面性を補償している可能性があります。",subjective:"家・友人・扉を、外部の誰かだけでなく、自分自身の人格の一部として読む余地があります。",motifs:["家：人格全体の像となり得るが、個人的連想を優先","水：無意識のイメージと関連し得る","閉じた扉：まだ意識化されていない側面の可能性"],questions:["夢の水は、あなたにとって脅威ですか、それとも生きたものですか？","今の意識的な態度と、夢が示す態度はどう反対ですか？"]},synthesis:"両理論とも、夢の像をそのまま予言とは扱いません。フロイト的には連想の鎖と夢の加工、ユング的には現在の意識への補償を確かめるのが次の一歩です。"};
const theories=[{n:"01",title:"夢の場面を整理",body:"記憶された場面、人物、出来事、感情を分け、夢の中で何が強調されているかを確認します。"},{n:"02",title:"現在とのつながり",body:"最近の出来事や意識的な態度と照らし合わせ、夢が補っているものや反復している葛藤を探ります。"},{n:"03",title:"個人的な連想を優先",body:"同じ『水』でも意味は人によって異なります。一般的な象徴より、本人の経験と感覚を優先します。"}];
export default function Home(){const[dream,setDream]=useState("");const[context,setContext]=useState("");const[mood,setMood]=useState("奇妙");const[lens,setLens]=useState<Lens>("compare");const[result,setResult]=useState<Analysis|null>(null);const[initialResult,setInitialResult]=useState<Analysis|null>(null);const[finalResult,setFinalResult]=useState<Analysis|null>(null);const[activeEntryId,setActiveEntryId]=useState<number|null>(null);const[history,setHistory]=useState<Entry[]>([]);const[key,setKey]=useState("");const[showKey,setShowKey]=useState(false);const[loading,setLoading]=useState(false);const[hasDeepened,setHasDeepened]=useState(false);const[error,setError]=useState("");const[tab,setTab]=useState<"analyze"|"journal"|"method">("analyze");
useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem("dream-analyzer-journal")||"[]"))}catch{}},[]);const stats=useMemo(()=>({count:history.length,motifs:new Set(history.flatMap(x=>x.result.elements)).size}),[history]);
async function analyze(associations=""){
  if(!dream.trim()){setError("夢の内容を入力してください。");return}
  setLoading(true);setError("");setShowKey(false);
  const controller=new AbortController();
  const timeout=setTimeout(()=>controller.abort(),45000);
  try{
    let analysis=DEMO;
    if(key.trim()){
      const prompt=`あなたは精神分析史に慎重な夢分析アシスタントです。診断・予言・断定をしません。夢辞典式の固定解釈は禁止です。\n夢: ${dream}\n目覚めた時の気分: ${mood}\n最近の状況: ${context||"未記入"}\n分析後の問いに対する本人の自由連想: ${associations||"まだ回答なし"}\n回答がある場合は必ずそれを優先して分析を更新し、同じ質問を繰り返さない。内部検討では、顕在内容/潜在的夢思考、自由連想、凝縮、置換、補償機能、主観水準、個人的連想、元型的モチーフを別々に検討したうえで、synthesisに矛盾を整理した一つの読み解きを作る。出力では人物名、学派名、理論名、二つの視点という表現を一切使わない。日本語で指定JSONのみ返す。`;
      const schema={type:"object",properties:{summary:{type:"string"},elements:{type:"array",items:{type:"string"}},freud:{type:"object",properties:{manifest:{type:"string"},latent:{type:"string"},mechanisms:{type:"array",items:{type:"string"}},questions:{type:"array",items:{type:"string"}}},required:["manifest","latent","mechanisms","questions"],additionalProperties:false},jung:{type:"object",properties:{compensation:{type:"string"},subjective:{type:"string"},motifs:{type:"array",items:{type:"string"}},questions:{type:"array",items:{type:"string"}}},required:["compensation","subjective","motifs","questions"],additionalProperties:false},synthesis:{type:"string"}},required:["summary","elements","freud","jung","synthesis"],additionalProperties:false};
      const res=await fetch("https://api.openai.com/v1/responses",{method:"POST",signal:controller.signal,headers:{"Content-Type":"application/json",Authorization:`Bearer ${key.trim()}`},body:JSON.stringify({model:"gpt-5-mini",input:prompt,text:{format:{type:"json_schema",name:"dream_analysis",strict:true,schema}}})});
      if(!res.ok){const detail=await res.json().catch(()=>null);throw new Error(detail?.error?.message||`API error ${res.status}`)}
      const data=await res.json();
      const outputText=data.output_text||data.output?.flatMap((x:{content?:Array<{type?:string;text?:string}>})=>x.content||[]).find((x:{type?:string})=>x.type==="output_text")?.text;
      if(!outputText)throw new Error("分析結果が空でした。");
      analysis=JSON.parse(outputText);
    }
    setResult(analysis);setShowKey(false);setHasDeepened(Boolean(associations));
    if(associations){setFinalResult(analysis)}else{setInitialResult(analysis);setFinalResult(null)}
    setTimeout(()=>document.querySelector(associations?".finalDiagnosis":".results")?.scrollIntoView({behavior:"smooth",block:"start"}),80);
    let next:Entry[];
    if(associations&&activeEntryId!==null){next=history.map(x=>x.id===activeEntryId?{...x,finalResult:analysis,associations}:x)}else{const id=Date.now();setActiveEntryId(id);const entry:Entry={id,date:new Date().toISOString(),title:dream.trim().slice(0,22),dream,mood,lens,result:analysis,initialResult:analysis};next=[entry,...history]}
    setHistory(next);
    try{localStorage.setItem("dream-analyzer-journal",JSON.stringify(next))}catch{setError("分析は完了しましたが、端末への保存容量が不足しています。")}
  }catch(err){
    const message=err instanceof Error?err.message:"不明なエラー";
    setError(err instanceof DOMException&&err.name==="AbortError"?"分析が45秒以内に完了しませんでした。もう一度お試しください。":`分析できませんでした：${message}`);
  }finally{
    clearTimeout(timeout);setLoading(false);
  }
}
return <main><header className="topbar"><button className="brand" onClick={()=>setTab("analyze")}><span className="mark">◐</span><span>DREAM<br/>ANALYZER</span></button><nav>{(["analyze","journal","method"] as const).map(t=><button key={t} className={tab===t?"active":""} onClick={()=>setTab(t)}>{t==="analyze"?"分析":t==="journal"?"記録":"方法論"}</button>)}</nav><button className="keyButton" onClick={()=>setShowKey(!showKey)}>{key?"API CONNECTED":"BYOK / API KEY"}</button></header>{showKey&&<><button className="keyBackdrop" aria-label="APIキーパネルを閉じる" onClick={()=>setShowKey(false)}/><div className="keyPanel"><button className="keyClose" aria-label="閉じる" onClick={()=>setShowKey(false)}>×</button><label>OPENAI API KEY<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="sk-…（保存されません）"/></label><p>キーはブラウザ内だけで使用し、保存しません。未入力でもデモ分析を試せます。</p><button className="keyDone" onClick={()=>setShowKey(false)}>設定を閉じる</button></div></>}
{tab==="analyze"&&<><section className="hero"><div className="orb"><i/><i/><i/></div><p className="kicker">DREAM ANALYZER v0.1</p><h1><em>深層心理夢占い</em></h1><p className="lede">夢に現れた人物・場所・出来事・感情から、心の奥にあるものを一つの読み解きとして提示します。</p></section><section className="workspace"><div className="inputCard"><div className="sectionLabel"><span>01</span>DREAM REPORT</div><label>どんな夢を見ましたか？<textarea value={dream} onChange={e=>setDream(e.target.value)} placeholder="覚えている場面、人物、言葉、色、感覚を、順序を気にせず書いてください…"/></label><div className="row"><label>目覚めた時の感情<select value={mood} onChange={e=>setMood(e.target.value)}><option>奇妙</option><option>不安</option><option>穏やか</option><option>喜び</option><option>悲しみ</option><option>混乱</option></select></label><label>最近の出来事・気がかり<input value={context} onChange={e=>setContext(e.target.value)} placeholder="任意。分析の精度を高めます"/></label></div>{error&&<p className="error">{error}</p>}<button className="analyze" onClick={()=>analyze()} disabled={loading}>{loading?"ANALYZING…":"夢を占う"}<b>→</b></button></div><aside className="side"><div className="sectionLabel"><span>METHOD</span>HOW IT READS</div>{theories.map(t=><article key={t.n}><b>{t.n}</b><div><h3>{t.title}</h3><p>{t.body}</p></div></article>)}<p className="notice">これは医療診断・心理療法・未来予測ではありません。強い苦痛が続く場合は専門家へご相談ください。</p></aside></section>{initialResult&&<><DiagnosisTimeline initial={initialResult} final={finalResult}/>{hasDeepened?<AnalysisClosure/>:<Questionnaire questions={[...initialResult.freud.questions,...initialResult.jung.questions]} loading={loading} onSubmit={answers=>analyze(answers)}/>}</>}</>}
{tab==="journal"&&<section className="page journalPage"><p className="kicker">PRIVATE / LOCAL JOURNAL</p><h1>夢の記録</h1><div className="journalActions"><div className="stats"><div><b>{stats.count}</b><span>DREAMS</span></div><div><b>{stats.motifs}</b><span>RECORDED ELEMENTS</span></div></div><JournalExport history={history}/></div><DreamSeries history={history} apiKey={key}/>{history.length===0?<p className="empty">まだ記録はありません。</p>:<div className="journal">{history.map(x=><article key={x.id}><time>{new Date(x.date).toLocaleDateString("ja-JP")}</time><h3>{x.title}</h3><p>{x.finalResult?.summary??x.initialResult?.summary??x.result.summary}</p>{x.finalResult&&<small className="hasFollowup">初診＋再診断</small>}<button onClick={()=>{const initial=x.initialResult??x.result;setDream(x.dream);setMood(x.mood);setInitialResult(initial);setFinalResult(x.finalResult??null);setResult(x.finalResult??initial);setActiveEntryId(x.id);setHasDeepened(Boolean(x.finalResult));setLens(x.lens);setTab("analyze")}}>診断を開く →</button></article>)}</div>}</section>}{tab==="method"&&<Approach/>}<footer><span>DREAM ANALYZER</span><p>Interpretation is a hypothesis, not a verdict.</p><small>© 2026 MASATO LAB</small></footer></main>}
function ResultView({result,lens}:{result:Analysis,lens:Lens}){return <section className="results"><div className="sectionLabel"><span>02</span>ANALYSIS REPORT</div><h2>{result.summary}</h2><div className="tags">{result.elements.map(x=><span key={x}>{x}</span>)}</div><div className="columns">{lens!=="jung"&&<article className="report freud"><header><span>F</span><div><small>SIGMUND FREUD</small><h3>夢の仕事をたどる</h3></div></header><h4>顕在内容</h4><p>{result.freud.manifest}</p><h4>潜在的夢思考への手がかり</h4><p>{result.freud.latent}</p><h4>検討される機制</h4><ul>{result.freud.mechanisms.map(x=><li key={x}>{x}</li>)}</ul><h4>自由連想の問い</h4><ol>{result.freud.questions.map(x=><li key={x}>{x}</li>)}</ol></article>}{lens!=="freud"&&<article className="report jung"><header><span>J</span><div><small>C. G. JUNG</small><h3>補償と象徴を読む</h3></div></header><h4>補償機能</h4><p>{result.jung.compensation}</p><h4>主観水準</h4><p>{result.jung.subjective}</p><h4>モチーフ（仮説）</h4><ul>{result.jung.motifs.map(x=><li key={x}>{x}</li>)}</ul><h4>個人的連想の問い</h4><ol>{result.jung.questions.map(x=><li key={x}>{x}</li>)}</ol></article>}</div><div className="synthesis"><span>SYNTHESIS</span><p>{result.synthesis}</p></div></section>}
function Method(){return <section className="page methodPage"><p className="kicker">THEORETICAL TRACE</p><h1>理論を混ぜず、<br/>並べて読む。</h1><p className="intro">DREAM ANALYZERは「フロイトもユングも象徴を解読した」という粗いまとめを避けます。両者の出発点・手続き・目的の違いを保ったまま、一つの夢に二つの問いを向けます。</p><div className="comparison"><article><small>FREUD / 1900</small><h2>願望と夢の加工</h2><p>記憶された夢（顕在内容）を入口に、夢を見る人自身の自由連想をたどります。潜在的な夢思考が、凝縮・置換・表象可能性・二次加工によって別の形を取った可能性を検討します。</p></article><article><small>JUNG / CW 8</small><h2>補償と自己調整</h2><p>夢を意識的態度への補償として読みます。登場人物を夢見る人の人格の一側面としてみる主観水準、個人的連想、反復する典型的モチーフを検討します。</p></article></div><div className="principles"><h2>分析原則</h2><ol><li><b>固定的な夢辞典を使わない。</b><span>象徴の意味を一対一で決めません。</span></li><li><b>本人の連想を先に聞く。</b><span>水、家、死などの一般論より、個人的経験を優先します。</span></li><li><b>仮説として提示する。</b><span>分析は診断でも、未来の予言でもありません。</span></li><li><b>理論の限界を明示する。</b><span>歴史的に重要な理論であり、現代科学の確定事項ではありません。</span></li></ol></div><div className="sources"><h2>参照した原典・資料</h2><a href="https://www.gutenberg.org/ebooks/66048" target="_blank">Sigmund Freud, The Interpretation of Dreams (1900) ↗</a><a href="https://www.gutenberg.org/ebooks/75333" target="_blank">Sigmund Freud, On Dreams (1901) ↗</a><a href="https://iaap.org/resources/academic-resources/collected-works-abstracts/volume-8-structure-dynamics-psyche/" target="_blank">C. G. Jung, Collected Works Vol. 8 — IAAP abstracts ↗</a><a href="https://archive.org/details/B-001-004-443-ALL" target="_blank">C. G. Jung et al., Man and His Symbols (1964) ↗</a></div></section>}
